language: c
sudo: false
compiler: gcc
script:
 - make
 - make uncomment
 - make pretty
 - out/ecpp examples/foreach.c
 - out/ecpp examples/pow.c
 - out/ecpp examples/prettyprinter.c
 - out/ecpp examples/print.c
 - out/ecpp examples/ptr.c
 - out/ecpp examples/return.c
 - out/pretty examples/prettyprinter.c
 - out/uncomment examples/comments.c
 - gcov src/*.c

after_success: 
 - bash <(curl -s https://codecov.io/bash)
